name: dhall-directory-tree
description: Generate a directory tree from a Dhall file
author: Nikita Volkov
branding:
  color: blue
inputs:
  dhall_file:
    description: Path to the source Dhall file
    required: true
  output_dir:
    description: Path to the output directory
    required: false
    default: .
runs:
  using: docker
  image: docker://ghcr.io/nikita-volkov/dhall-directory-tree.github-action:61b20496c786e081a0778755afe8e0ed5ee58c58
  env:
    dhall_file: ${{ inputs.dhall_file }}
    output_dir: ${{ inputs.output_dir }}
